import React, { useEffect, useContext, useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Tooltip } from '@mui/material';
import { MainContext } from '../context/MainContext';
import fakeWeeklyLogData from '../data/fakeWeeklyLogData.json'; 
import { SHIP_NAME } from '../libs/Constants';

// 🟢 Constants
const shipName = SHIP_NAME || "Unknown Ship";
const userName = "user";

export const ExportPdfButton = ({ theme }) => {
  const { weeklyLogs, sendMessage, isDemo } = useContext(MainContext);
  const [isFetching, setIsFetching] = useState(false);

  // 🔘 User clicked export
  const fetchPastData = () => {
    console.log("Requesting past 7 days data...");
    setIsFetching(true);

    if (isDemo) {
      console.log("Demo mode active — using fakeWeeklyLogData.json");
      // Simulate async backend fetch
      setTimeout(() => {
        setIsFetching(false);
        generateWeeklyReport(fakeWeeklyLogData);
      }, 500);
    } else {
      // Real data request
      sendMessage({ PAST: true });
    }
  };

  // 🧩 Handle backend response
  useEffect(() => {
    if (!isDemo && isFetching && weeklyLogs && Object.keys(weeklyLogs).length > 0) {
      console.log("✅ Past data received from backend:", weeklyLogs);
      setIsFetching(false);
      generateWeeklyReport(weeklyLogs);
    }
  }, [weeklyLogs]);

  // 📅 Format timestamp
  const formatTime = (timestamp) => {
    if (!timestamp) return "";
    const date = new Date(timestamp);
    return date.toLocaleString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
  };

  // 🧾 Generate Weekly PDF
  const generateWeeklyReport = async (logsData) => {
    if (!logsData || logsData.length === 0) {
      alert("No data available to export!");
      return;
    }
  
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const formattedDate = new Date().toLocaleString();
  
    // 🖼️ Load PNG logo
    try {
      const img = new Image();
      img.src = '/static/images/redraven.png';
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });
  
      doc.addImage(img, 'PNG', 5, 10, 20, 20); // slightly bigger logo
    } catch (err) {
      console.error("⚠️ Failed to load logo:", err);
    }
  
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('Weekly Report', pageWidth - 5, 18, { align: 'right' });
    doc.setFontSize(12);
    doc.text(`${shipName}`, pageWidth - 5, 26, { align: 'right' });
  
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Generated on:`, 5, 45);
    doc.setFont('helvetica', 'normal');
    doc.text(`${formattedDate}`, 33, 45);
  
    doc.setFont('helvetica', 'bold');
    doc.text(`Generated by:`, 5, 49);
    doc.setFont('helvetica', 'normal');
    doc.text(`${userName}`, 33, 49);
  
    // 🧱 Table Data
    const tableBody = [];

logsData.forEach(node => {
  const nodeId = node.nodeId || "N/A";
  const compartment = node.compno ?? "N/A";
  const deck = node.deckno ?? "N/A";
  const deviceType = node.nodeType || "N/A";

  const tempLogs = node.logs?.alertlogstemp || [];
  const batteryLogs = node.logs?.alertlogsbattery || [];

  // 🗓️ Merge all logs by date (YYYY-MM-DD)
  const dailyLogs = {};

  tempLogs.forEach(log => {
    const date = new Date(log.timestamp).toISOString().split('T')[0];
    if (!dailyLogs[date]) dailyLogs[date] = {};
    dailyLogs[date].temp = `${log.message} (${log.value ?? ""})`;
    dailyLogs[date].timestamp = log.timestamp;
  });

  batteryLogs.forEach(log => {
    const date = new Date(log.timestamp).toISOString().split('T')[0];
    if (!dailyLogs[date]) dailyLogs[date] = {};
    dailyLogs[date].battery = `${log.message} (${log.value ?? ""})`;
    dailyLogs[date].timestamp = log.timestamp;
  });

    // 🧩 Convert daily logs to table rows
    const dates = Object.keys(dailyLogs).sort(); // chronological order
    dates.forEach((date, index) => {
      const entry = dailyLogs[date];
      tableBody.push([
        index === 0 ? nodeId : "", // merge nodeId visually
        compartment,
        deck,
        deviceType,
        formatTime(entry.timestamp),
        entry.battery || "",
        entry.temp || "",
      ]);
    });
  });
  
    // 📊 Render Table (aligned evenly)
    doc.autoTable({
      startY: 60,
      margin: { left: 5, right:  5 }, // tighter margins
      head: [['Device Id', 'Compartment', 'Deck', 'Device Type', 'Time', 'Battery Log', 'Temperature Log']],
      body: tableBody,
      theme: 'grid',
      styles: {
        fontSize: 9,
        halign: 'center',
        valign: 'middle',
        lineColor: [0, 0, 0],
        lineWidth: 0.2,
        minCellHeight: 10,
      },
      headStyles: {
        fillColor: [220, 53, 69],
        textColor: 255,
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 25 },
        2: { cellWidth: 20 },
        3: { cellWidth: 25 },
        4: { cellWidth: 35 },
        5: { cellWidth: 35 },
        6: { cellWidth: 35 },
      },
    });
  
    const finalY = doc.autoTable.previous.finalY || 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Checked by:' ,5, finalY + 20);

    try {
      const logo = new Image();
      logo.src = '/static/images/crimsonenergy.png';
      await new Promise((resolve, reject) => {
        logo.onload = resolve;
        logo.onerror = reject;
      });
    
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight(); // full page height
      const logoWidth = 10;                      // width in mm
      const logoHeight = logoWidth / 1.53;       // maintain aspect ratio
      const logoX = pageWidth - logoWidth - 5;   // right margin
      const logoY = pageHeight - logoHeight - 5; // bottom margin (5mm)
    
      doc.addImage(logo, 'PNG', logoX, logoY, logoWidth, logoHeight);
    } catch (err) {
      console.error('⚠️ Failed to load Crimson Energy logo:', err);
    }
  
    // 💾 Save
    doc.save(`Redraven Weekly Report (${formattedDate}).pdf`);
  };

  return (
    <Tooltip title={isDemo ? "Generate Demo Weekly Report" : "Generate Weekly Report"} disableInteractive>
      <div
        onClick={!isFetching ? fetchPastData : undefined}
        className="header-icon-div"
        style={{
          cursor: isFetching ? 'not-allowed' : 'pointer',
          opacity: isFetching ? 0.6 : 1,
        }}
      >
        <img src="/static/images/report.svg" alt="report-icon" />
      </div>
    </Tooltip>
  );
};
